### ISSUE TITLE
I would like to get a hold of you

### ISSUE THREAD

**Issue by NeedToLearn101** [AndreasBomholtz/Underboss#6]
Hello there Sir,

I hope you're in a good health, I would like to take some of your time to admire the great work you have done with this piece of work.

I'm highly interested in the bot, I would like to develop it although I have no experience in Javascript nor API(I know a lil about python&javascript not past the beginner level though) but I'm really willing to go for it and I have been doing research. I feel like I can though with understanding how the open source work. I have been sniffing with F12 in the game and I think that's how it works now ( found your cool github on the 3rd of Dec, sadly I was having my tests at that time xD)

I have been researching to find a way to make a bot for the game but had no luck at finding a way that people explain to how work with the page's api to trigger some commands.

I come to guess that you need some kind of server for the bot using .NET to secure the bot I would assume, and making a google extension.

Can you please lemme know what do I need to be able to develop it since the game has been moved to Facebook.

I would like to use your script and somehow make it as a google extension and linked with a server using .NET to be able to give access to others.

You could say that I want to be your Apprentice/student to learn from the best

PS( the issue :) ). the bot doesn't show up while using greasemonkey after tweaking @include to match the url with Facebook.

Thank you for your time!

have a nice day.

Yours,
MT8

**Comment by AndreasBomholtz** [comment]
Hi,

I'm happy that you are interested in my bot. As you can see I have not worked on this for the last 2 years.

So it will not work, because they moved the game to facebook. So there is some work to be done to get it to work again.

The bot works by running in JS in the browser, so there is no need for a server or anything.

A google chrome extension is just JS so you should be able to just port it.

I maybe have some time to look at it, so that it can run in facebook.

Best regards,
Andreas

**Comment by AndreasBomholtz** [comment]
Hi,

I just updated the bot, so now it can run on facebook :)

**Comment by NeedToLearn101** [comment]
Hello there,

Thank you for your fast reply and the fast update. much appreciated

I have pasted the code in underboss.user.js into the tampermonkey extensions, it shows as the script is enabled but the bot isn't there, it doesn't show up.

**Comment by AndreasBomholtz** [comment]
I tested it today with Chrome and tamper monkey (beta).

Can you see something in the developer console? Some errors or something,
that could guide me to what is wrong.

When I tested it, I saw that there are a few errors, probably due to the
move to Facebook.

In the script you pasted in, does it have the @include for Facebook?

Den 31. jan. 2018 17.01 skrev "MT8" <notifications@github.com>:

**Comment by NeedToLearn101** [comment]
Well I changed the @include to include facebook, like this ;

`// @include     https://apps.facebook.com/play_godfather*
// @include     https://apps.facebook.com/*/play_godfather*
//@include      https://apps.facebook.com/play_godfather/server/195*

and here are the errors http://prntscr.com/i88r15`

**Comment by AndreasBomholtz** [comment]
Sorry, I forgot to create a release. It should be updated now. Please try to copy the new version.

**Comment by NeedToLearn101** [comment]
np, I will test it now

**Comment by NeedToLearn101** [comment]
Yup it worked!!

Much appreciated

wanna join back ? :)

**Comment by AndreasBomholtz** [comment]
I'm glad that it is working now. There are some issues that has to be solved, but I hope that you can use it.

I do not know what you mean by 'join back'?

**Comment by NeedToLearn101** [comment]
I meant play again if you ever did :)

**Comment by AndreasBomholtz** [comment]
Hehe, I might. Just to test the bot.
